### ISSUE TITLE
no location specified for some office hours

### ISSUE THREAD

**Issue by sxlijin** [vuse-cs3251/vuse-cs3251.github.io#9]
Venki and Ram need to specify locations for their office hours.

**Comment by venkatvandy** [comment]
My office hours
Monday --> 12 - 1:30
Friday     --> 2 - 4

**Comment by sxlijin** [comment]
@venkatvandy we need you to specify *where* you'll be holding office hours, not when. I've already [added that info to the page](https://vuse-cs3251.github.io/instructors-and-hours/).

**Comment by ramanathnk** [comment]
My office hours will be in the room 314
